name: Ubuntu Automatic CI

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop
  
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: install pip
      run: sudo apt update && sudo apt install python3-pip && sudo apt install libgl-dev
      
    - name: Install conan
      run: pip install conan
      
    - name: Add conan to PATH
      run: cd ~/ && ls && export PATH="$PATH:/home/.local/bin"
      
    - name: Setup conan
      run: conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan && conan config set general.revisions_enabled=1
      
    - name: Build
      run: mkdir build && cd build && conan install --build missing .. && conan install --build missing .. && cmake .. && cmake --build . --config Release

    - name: Check R-TYPE server binary exist
      uses: andstor/file-existence-action@v1
      with:
        files: "build/bin/rtype_server.exe"
    
    - name: Check R-TYPE client binary exist
      uses: andstor/file-existence-action@v1
      with:
        files: "build/bin/rtype_client.exe"
